### PR TITLE
feat(ci): upload goreleaser dist

### PR DESCRIPTION
**Pull request by aymanbagabas**
upload the dist directory after running goreleaser on release, nightly, and snapshots

### CODE REVIEW

**Comment by caarlos0** [comment]
lgtm, but idk why are we doing it?

**Comment by caarlos0** [comment]
is this still needed

**Comment by aymanbagabas** [comment]
> is this still needed

Yes, would be nice to have

**Comment by caarlos0** [comment]
but why? what's the usecase?

**Comment by caarlos0** [comment]
hmmm gotcha... do we have to pay for that space? if so, I can see it getting big really fast... 

also worth noting that I'm working in a feature to not fail the entire pipeline if some parts of it fail (like aur)... and will probably then print the file, or add a way to store them somewhere else... haven't decided yet -> https://github.com/goreleaser/goreleaser/issues/3989

**Pull request merged**
